name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.18', '1.17']
        os: ['ubuntu-latest']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build containers
      run: docker compose build

    - name: Start services
      run: docker compose up -d db

    - name: Wait for DB (healthcheck)
      run: |
        echo "Aguardando PostgreSQL..."
        until [ "$(docker inspect --format='{{json .State.Health.Status}}' curso_ci_2-db-1)" = "\"healthy\"" ]; do
          sleep 2
        done

    - name: Run tests
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASS: root
        DB_NAME: root
      run: |
        go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker compose build









